import { defineUnthemeConfig } from "untheme";
import { useColorPack, referenceColorTokens } from "@untheme/colors";

export default defineUnthemeConfig({
  tokens: {
    // colors
    "sr-black": "#000",
    "sr-white": "#FFF",
    ...useColorPack(
      "tw",
      [
        "amber",
        "blue",
        "cyan",
        "emerald",
        "fuchsia",
        "gray",
        "green",
        "indigo",
        "lime",
        "neutral",
        "orange",
        "pink",
        "purple",
        "red",
        "rose",
        "sky",
        "slate",
        "stone",
        "teal",
        "violet",
        "yellow",
        "zinc",
      ],
      "-",
    ),
    // spacing
    "spacing-2xs": "4px",
    "spacing-xs": "8px",
    "spacing-s": "12px",
    "spacing-m": "16px",
    "spacing-l": "20px",
    "spacing-xl": "24px",
    "spacing-2xl": "28px",
    // shape
    "shape-none": "0px",
    "shape-xs": "2px",
    "shape-s": "4px",
    "shape-m": "6px",
    "shape-l": "8px",
    "shape-xl": "12px",
    "shape-full": "9999px",
    // typeface
    "typeface-archivo": "Archivo",
    "typeface-inter": "Inter",
    // typesize
    "typesize-heading-1": "1.5em",
    "typesize-heading-2": "1.25em",
    "typesize-heading-3": "1em",
    "typesize-heading-4": "0.875em",
    "typesize-heading-5": "0.75em",
    "typesize-heading-6": "0.6875em",
    "typesize-title-s": "0.875em",
    "typesize-title-m": "1em",
    "typesize-title-l": "1.125em",
    "typesize-body-s": "0.6875em",
    "typesize-body-m": "0.875em",
    "typesize-body-l": "1em",
  },
  themes: {
    company: {
      ...referenceColorTokens("tw", "emerald", "primary", "-"),
      ...referenceColorTokens("tw", "stone", "surface", "-"),
      ...referenceColorTokens("tw", "rose", "error", "-"),
      "typeface-content": "typeface-inter",
    },
    example: {
      ...referenceColorTokens("tw", "fuchsia", "primary", "-"),
      ...referenceColorTokens("tw", "slate", "surface", "-"),
      ...referenceColorTokens("tw", "red", "error", "-"),
      "typeface-content": "typeface-archivo",
    },
  },
  modes: {
    dark: {
      "neutral-fg-2xh": "tw-surface-50",
      "neutral-fg-xh": "tw-surface-100",
      "neutral-fg-h": "tw-surface-300",
      "neutral-fg-m": "tw-surface-500",
      "neutral-fg-l": "tw-surface-700",
      "neutral-fg-xl": "tw-surface-800",
      "neutral-fg-2xl": "tw-surface-950",
      "neutral-bg-h": "tw-surface-950",
      "neutral-bg-m": "tw-surface-900",
      "neutral-bg-l": "tw-surface-800",
      "neutral-bg-xl": "tw-surface-700",
      "neutral-ct-xh": "sr-black",
      "neutral-ct-h": "tw-surface-950",
      "neutral-ct-m": "tw-surface-900",
      "neutral-ct-l": "tw-surface-800",
      "neutral-ct-xl": "tw-surface-700",
      "primary-fg-h": "sr-black",
      "primary-fg-m": "tw-primary-950",
      "primary-fg-l": "tw-primary-900",
      "primary-bg-h": "tw-primary-300",
      "primary-bg-m": "tw-primary-400",
      "primary-bg-l": "tw-primary-500",
      "tonal-fg-h": "tw-primary-500",
      "tonal-fg-m": "tw-primary-400",
      "tonal-fg-l": "tw-primary-300",
      "tonal-bg-h": "tw-primary-950",
      "tonal-bg-m": "tw-primary-900",
      "tonal-bg-l": "tw-primary-800",
      "error-fg-h": "sr-black",
      "error-fg-m": "tw-error-950",
      "error-fg-l": "tw-error-900",
      "error-bg-h": "tw-error-300",
      "error-bg-m": "tw-error-400",
      "error-bg-l": "tw-error-500",
      "error-tonal-fg-h": "tw-error-400",
      "error-tonal-fg-m": "tw-error-300",
      "error-tonal-fg-l": "tw-error-200",
      "error-tonal-bg-h": "tw-error-950",
      "error-tonal-bg-m": "tw-error-900",
      "error-tonal-bg-l": "tw-error-800",
    },
    light: {
      "neutral-fg-2xh": "tw-surface-950",
      "neutral-fg-xh": "tw-surface-900",
      "neutral-fg-h": "tw-surface-700",
      "neutral-fg-m": "tw-surface-500",
      "neutral-fg-l": "tw-surface-400",
      "neutral-fg-xl": "tw-surface-200",
      "neutral-fg-2xl": "tw-surface-50",
      "neutral-bg-h": "tw-surface-50",
      "neutral-bg-m": "tw-surface-100",
      "neutral-bg-l": "tw-surface-200",
      "neutral-bg-xl": "tw-surface-300",
      "neutral-ct-xh": "tw-surface-50",
      "neutral-ct-h": "tw-surface-100",
      "neutral-ct-m": "tw-surface-200",
      "neutral-ct-l": "tw-surface-300",
      "neutral-ct-xl": "tw-surface-400",
      "primary-fg-h": "tw-primary-50",
      "primary-fg-m": "tw-primary-100",
      "primary-fg-l": "tw-primary-200",
      "primary-bg-h": "tw-primary-600",
      "primary-bg-m": "tw-primary-700",
      "primary-bg-l": "tw-primary-800",
      "tonal-fg-h": "tw-primary-900",
      "tonal-fg-m": "tw-primary-900",
      "tonal-fg-l": "tw-primary-950",
      "tonal-bg-h": "tw-primary-300",
      "tonal-bg-m": "tw-primary-200",
      "tonal-bg-l": "tw-primary-400",
      "error-fg-h": "tw-error-50",
      "error-fg-m": "tw-error-100",
      "error-fg-l": "tw-error-200",
      "error-bg-h": "tw-error-600",
      "error-bg-m": "tw-error-700",
      "error-bg-l": "tw-error-800",
      "error-tonal-fg-h": "tw-error-900",
      "error-tonal-fg-m": "tw-error-800",
      "error-tonal-fg-l": "tw-error-700",
      "error-tonal-bg-h": "tw-error-100",
      "error-tonal-bg-m": "tw-error-200",
      "error-tonal-bg-l": "tw-error-300",
    },
  },
  roles: {
    // component tokens should go here
  },
});
